name: menufic
type: application
description: Menufic is a digital menu generator for restaurants that makes it simple and easy for anyone to create and share their restaurant menus.
version: 1.0.0
apiVersion: v2
keywords:
    - menufic
    - menu
    - restaurant
maintainers:
    - name: Andrew Montoya
      email: halossqwerty@gmail.com
      url: haloss1.me
sources:
    - "https://github.com/kaje94/menufic"

dependencies:
    - condition: mariadb.enabled
      name: mariadb
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 18.x.x
