{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" .Release.Name .Chart.Name }}
  annotations: {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{ if .Values.ingress.tls -}}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ printf "%s-%s" .Release.Name .Chart.Name }}
            port:
              number: {{ .Values.service.port }}
{{- end }}