import { type NextPage } from "next";
import Head from "next/head";
import { SimpleGrid, Title, Text, Loader, Center, Box } from "@mantine/core";
import { AppShell } from "src/components/AppShell";
import { ImageCard } from "src/components/Cards";
import { api } from "src/utils/api";
import { Empty } from "src/components/Empty";
import { useAutoAnimate } from "@formkit/auto-animate/react";
import { showErrorToast } from "src/utils/helpers";

/** Page that will allow logged in users to view all of the published restaurant menus */
const ExplorePage: NextPage = () => {
    const { data: restaurants = [], isLoading } = api.restaurant.getAllPublished.useQuery(undefined, {
        onError: () => showErrorToast("Failed to retrieve published restaurants"),
    });
    const [itemsParent] = useAutoAnimate<HTMLDivElement>();
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
            </Head>
            <main>
                <AppShell>
                    <Title order={1}>Explore Restaurants</Title>
                    <Text color="dimmed">Following are the restaurants published by all users</Text>
                    <Box ref={itemsParent}>
                        <SimpleGrid
                            mt="lg"
                            breakpoints={[
                                { minWidth: "xl", cols: 3 },
                                { minWidth: "md", cols: 2 },
                                { minWidth: "sm", cols: 1 },
                            ]}
                        >
                            {restaurants?.map((item) => (
                                <ImageCard
                                    key={item.id}
                                    image={item.image}
                                    href={`/restaurant/${item.id}/menu`}
                                    title={item.name}
                                    subTitle={item.location}
                                    target="_blank"
                                />
                            ))}
                        </SimpleGrid>
                        {isLoading && (
                            <Center w="100%" h="50vh">
                                <Loader size="lg" />
                            </Center>
                        )}
                        {!isLoading && restaurants?.length === 0 && (
                            <Empty text="There aren't any published restaurants" height="50vh" />
                        )}
                    </Box>
                </AppShell>
            </main>
        </>
    );
};

export default ExplorePage;
