import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, useSession } from "next-auth/react";

import { Box, Button, Container, Stack, Text } from "@mantine/core";

const Landing: NextPage = () => {
    const { data: sessionData } = useSession();
    return (
        <>
            <Head>
                {/** TODO: update tags for dashboard */}
                <title>Menufic</title>
                <meta name="description" content="Generated by create-t3-app" />
            </Head>

            <Container h="100vh">
                <Stack h="100%" align="center" justify="center">
                    {sessionData?.user !== undefined ? (
                        <>
                            <Box>
                                <Text>Logged in as {sessionData?.user?.name}</Text>
                            </Box>
                            <Link href="/restaurant">
                                <Button size="lg">Open Dashboard</Button>
                            </Link>
                        </>
                    ) : (
                        <Button onClick={() => signIn("google", { callbackUrl: "/restaurant" })} size="lg">
                            Login
                        </Button>
                    )}
                </Stack>
            </Container>
        </>
    );
};

export default Landing;
