import { type NextPage } from "next";
import Head from "next/head";
import { SimpleGrid, Text, Breadcrumbs, Box, Center, Loader } from "@mantine/core";
import { AppShell } from "src/components/AppShell";
import { ImageCard, IconCard } from "src/components/Cards";
import { BannerForm } from "src/components/Forms/BannerForm";
import type { FC } from "react";
import { useState } from "react";
import { api } from "src/utils/api";
import { DeleteConfirmModal } from "src/components/DeleteConfirmModal";
import type { Image } from "@prisma/client";
import Link from "next/link";
import { PublishButton } from "src/components/PublishButton";
import { useRouter } from "next/router";
import { showErrorToast, showSuccessToast } from "src/utils/helpers";
import { env } from "src/env/client.mjs";
import { useCommonStyles } from "src/styles/common";
import { useAutoAnimate } from "@formkit/auto-animate/react";
import { IconCirclePlus } from "@tabler/icons";

/** Page to manage banners of a selected restaurant */
const BannersPage: NextPage = () => {
    const router = useRouter();
    const { classes: commonClasses } = useCommonStyles();
    const [bannerFormOpen, setBannerFormOpen] = useState(false);
    const restaurantId = router.query?.restaurantId as string;
    const [gridItemParent] = useAutoAnimate<HTMLDivElement>();

    const { data: banners = [], isLoading: loadingBanners } = api.restaurant.getBanners.useQuery(
        { id: restaurantId },
        {
            enabled: !!restaurantId,
            onError: () => showErrorToast("Failed to retrieve banners"),
        }
    );

    const { data: restaurant, isLoading } = api.restaurant.get.useQuery(
        { id: restaurantId },
        {
            enabled: !!restaurantId,
            onError: () => {
                showErrorToast("Failed to retrieve restaurant details");
                router.push("/restaurant");
            },
        }
    );

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
            </Head>
            <main>
                <AppShell>
                    <Box>
                        {isLoading || loadingBanners ? (
                            <Center w="100%" h="50vh">
                                <Loader size="lg" />
                            </Center>
                        ) : (
                            <>
                                <SimpleGrid
                                    breakpoints={[
                                        { minWidth: "sm", cols: 2 },
                                        { minWidth: "xs", cols: 1 },
                                    ]}
                                >
                                    <Breadcrumbs>
                                        <Link href="/restaurant" className={commonClasses.link}>
                                            Restaurant
                                        </Link>
                                        <Link href={`/restaurant/${restaurant?.id}`} className={commonClasses.link}>
                                            {restaurant?.name}
                                        </Link>
                                        <Text>Banners</Text>
                                    </Breadcrumbs>
                                    {restaurant && <PublishButton restaurant={restaurant} />}
                                </SimpleGrid>
                                <SimpleGrid
                                    mt="md"
                                    breakpoints={[
                                        { minWidth: "xl", cols: 3 },
                                        { minWidth: "md", cols: 2 },
                                        { minWidth: "sm", cols: 1 },
                                    ]}
                                    ref={gridItemParent}
                                >
                                    {banners?.map((item) => (
                                        <BannerCard key={item.id} item={item} />
                                    ))}
                                    {banners &&
                                        banners?.length < Number(env.NEXT_PUBLIC_MAX_BANNERS_PER_RESTAURANT) && (
                                            <IconCard
                                                title="Add new banner"
                                                subTitle="Start creating a new restaurant menu by adding a new restaurant"
                                                onClick={() => setBannerFormOpen(true)}
                                                Icon={IconCirclePlus}
                                            />
                                        )}
                                </SimpleGrid>
                            </>
                        )}
                    </Box>
                </AppShell>

                {restaurant?.id && (
                    <BannerForm
                        opened={bannerFormOpen}
                        onClose={() => setBannerFormOpen(false)}
                        restaurantId={restaurant?.id}
                    />
                )}
            </main>
        </>
    );
};

// todo: check if following can be moved into components

/** ImageCard component that represents each banner with delete functionality */
const BannerCard: FC<{ item: Image }> = ({ item }) => {
    const trpcCtx = api.useContext();
    const router = useRouter();
    const [deleteFormOpen, setDeleteFormOpen] = useState(false);
    const restaurantId = router.query?.restaurantId as string;

    const { mutate: deleteRestaurant, isLoading: isDeleting } = api.restaurant.deleteBanner.useMutation({
        onSuccess: (data) => {
            trpcCtx.restaurant.getBanners.setData({ id: restaurantId }, (banners = []) =>
                banners.filter((item) => item.id !== data.id)
            );
            showSuccessToast("Successfully deleted", `Deleted the banner of the restaurant successfully`);
        },
        onError: (err) => showErrorToast("Failed to create banner", err),
    });

    return (
        <>
            <ImageCard
                image={item}
                editDeleteOptions={{
                    loading: isDeleting,
                    onDeleteClick: () => setDeleteFormOpen(true),
                }}
            />
            <DeleteConfirmModal
                opened={deleteFormOpen}
                onClose={() => setDeleteFormOpen(false)}
                onDelete={() => {
                    deleteRestaurant({ id: item.id });
                    setDeleteFormOpen(false);
                }}
                title="Delete restaurant banner?"
                description="Are you sure, you want to delete this restaurant banner? This action action cannot be undone"
            />
        </>
    );
};

export default BannersPage;
