import type { GetStaticPropsContext } from "next";
import { type NextPage } from "next";
import Head from "next/head";
import { Container } from "@mantine/core";
import { useRouter } from "next/router";
import { api } from "src/utils/api";
import { createProxySSGHelpers } from "@trpc/react-query/ssg";
import { appRouter } from "src/server/api/root";
import superjson from "superjson";
import { prisma } from "src/server/db";
import { RestaurantMenu } from "src/components/RestaurantMenu";
import { useSession } from "next-auth/react";
import { Footer } from "src/components/Footer";
import { showErrorToast } from "src/utils/helpers";

/** Restaurant menu page that will be shared publicly */
const RestaurantMenuPage: NextPage = () => {
    const router = useRouter();
    const { status } = useSession();
    const restaurantId = router.query?.restaurantId as string;

    const { data: restaurant } = api.restaurant.getDetails.useQuery(
        { id: restaurantId },
        {
            enabled: status === "authenticated" && !!restaurantId,
            onError: () => showErrorToast("Failed to retrieve restaurant details"),
        }
    );

    if (typeof window !== "undefined" && !restaurant) {
        router.replace("/404");
    }

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
            </Head>
            <main>
                <Container size="xl" py="lg">
                    {restaurant && <RestaurantMenu restaurant={restaurant} />}
                </Container>
            </main>
            <Footer />
        </>
    );
};

export default RestaurantMenuPage;

export async function getStaticProps(context: GetStaticPropsContext<{ restaurantId: string }>) {
    const ssg = createProxySSGHelpers({ router: appRouter, ctx: { session: null, prisma }, transformer: superjson });
    const restaurantId = context.params?.restaurantId as string;
    try {
        const restaurant = await ssg.restaurant.getDetails.fetch({ id: restaurantId });
        if (restaurant.isPublished) {
            // Only return restaurants that are published
            return { props: { trpcState: ssg.dehydrate(), restaurantId }, revalidate: 1800 }; // revalidate in 30 mins
        }
        return { props: { restaurantId } };
    } catch {
        return { props: { restaurantId }, revalidate: 1800 };
    }
}

export async function getStaticPaths() {
    // Skip building pages during build time
    return { paths: [], fallback: "blocking" };
}
